### PR TITLE
lint: Introduce scalafix Disable rules for partial (non-total) functions

### PR DESCRIPTION
**Pull request by sideeffffect**
I took inspiration from the [Scalazzi project](https://github.com/scalaz/scalazzi/blob/master/scalafix.conf)

### CODE REVIEW

**Comment by jakubjanecek** [comment]
In practice what does this do? I don't get the connection between `catchNonFatal` and URL encoding/decoding.

**Comment by sideeffffect** [comment]
the static methods (`encode`/`decode`) on these classes are not total, and in some cases throw
that's why calling these should be wrapped in `catchNonFatal`

**Comment by jakubjanecek** [comment]
I don't get why only these two methods are mentioned. There must be many such methods so why just these two were chosen? We are not even using them in our code. Point is that either the list should be "full" or such rule does not make much sense - anyone working with Java APIs will definitely wrap them properly because you never know when exceptions can be thrown.

**Comment by sideeffffect** [comment]
> why only these two methods

because nobody put in the effort to add more. any help/PRs will be heartily appreciated! This is just a start -- my personal plan is to add more functions as time goes by, typically those that are widely used and throw or have any other suspicious behavior.

**Pull request merged**
